"""04_filter_core.py -- complete-case view of analysis_clean.csv.

Keeps only rows where the 12 core measures are all populated. Tech-share
columns and footprint stay in the file but stay nullable (requiring them
would empty the table: no year has every technology measured, and footprint
starts in 2008). Dropped rows are counted by reason and appended to
reports/03_merge_report.md is NOT modified; drops are logged to
reports/04_core_filter.md instead.

Idempotent: rereads outputs/analysis_clean.csv, rewrites both outputs.
"""

import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "outputs")
REPORTS = os.path.join(HERE, "reports")

CORE = [
    "real_world_mpg", "real_world_mpg_city", "real_world_mpg_hwy",
    "cafe_2cycle_mpg", "weight_lbs", "horsepower_hp",
    "engine_displacement_cid", "accel_0_60_s", "ton_mpg_real_world",
    "hp_per_lb",
]
# EPA publishes no production volumes for the preliminary model year, so
# requiring them there would delete the entire prelim year and defeat the
# is_preliminary flag. Production is required only on final-data rows.
PROD = ["production_thousands", "production_share"]


def main():
    ac = pd.read_csv(os.path.join(OUT, "analysis_clean.csv"))
    complete = ac[CORE].notna().all(axis=1) & (
        ac["is_preliminary"] | ac[PROD].notna().all(axis=1)
    )
    kept = ac[complete].reset_index(drop=True)
    dropped = ac[~complete]

    kept.to_csv(os.path.join(OUT, "analysis_core.csv"), index=False, encoding="utf-8")

    # Per-column accounting of what caused each drop (a row can appear in
    # several columns' counts; the union is the dropped total).
    lines = [
        "# Core Filter Log\n",
        "Generated by 04_filter_core.py.\n",
        f"\nInput rows: {len(ac):,}. Kept: {len(kept):,}. "
        f"Dropped: {len(dropped):,} (row incomplete on a core measure, or "
        "missing production volume on a non-preliminary row; preliminary "
        "rows are exempt from the production requirement because EPA "
        "publishes no volumes for the preliminary year).\n",
        "\n| Core column | Null in dropped rows |\n|---|---|\n",
    ]
    for c in CORE + PROD:
        n = int(dropped[c].isna().sum())
        if n:
            lines.append(f"| `{c}` | {n:,} |\n")
    lines.append(
        f"\nDropped rows by year range: {int(dropped['model_year'].min())}-"
        f"{int(dropped['model_year'].max())}; mostly early-year manufacturer "
        "slices where EPA did not report a measure ('-' in the export) and "
        "manufacturers absent in given years (Tesla before 2011, Kia/Hyundai "
        "before US entry).\n"
        "\nColumns intentionally still nullable in analysis_core.csv: all "
        "`share_*` (technology not yet/no longer existing), `footprint_sqft` "
        "(collected from 2008), `avg_*`, and the four `catalog_*` columns "
        "(populated only on All/All-grain rows, and only 1984+).\n"
    )
    with open(os.path.join(REPORTS, "04_core_filter.md"), "w", encoding="utf-8") as f:
        f.writelines(lines)

    print(f"kept {len(kept):,} / {len(ac):,} rows -> outputs/analysis_core.csv")
    print(f"dropped {len(dropped):,}; log at reports/04_core_filter.md")


if __name__ == "__main__":
    main()
