"""06_external.py -- external context series, annualized and joined on year.

Inputs (downloaded from FRED, plain CSV, stored in external/):
  fred_gas_price.csv   APU000074714  BLS avg price, unleaded regular, $/gal, monthly, 1976+
  fred_cpi_all.csv     CPIAUCSL      CPI-U all items, monthly, 1947+
  fred_cpi_newveh.csv  CUUR0000SETA01  CPI new vehicles, monthly, 1947+
  fred_vmt.csv         TRFVOLUSM227NFWA  vehicle miles traveled, millions, monthly, 1970+

Output: outputs/context_annual.csv, one row per calendar year, plus
reports/06_external_sources.md documenting sources, units, and caveats.

CAFE passenger-car standards 1978-2010 are a small hardcoded table taken from
NHTSA's published standard levels (49 USC 32902 era, single national number
per year). From MY2011 the standard is footprint-based per-fleet and has no
single MPG value, so those years are left null on purpose.

Caveat recorded in the report: calendar year != model year. Model year N
vehicles mostly sell during calendar N-1..N; joining calendar-year context to
model-year fleet data is standard practice but is an approximation, not an
exact alignment.
"""

import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
EXT = os.path.join(HERE, "external")
OUT = os.path.join(HERE, "outputs")
REPORTS = os.path.join(HERE, "reports")

# NHTSA passenger-car CAFE standards, single national values, MY1978-2010.
# 1986-1988 were administratively lowered to 26.0, restored 27.5 by 1990.
CAFE_CAR_STANDARD = {
    1978: 18.0, 1979: 19.0, 1980: 20.0, 1981: 22.0, 1982: 24.0, 1983: 26.0,
    1984: 27.0, 1985: 27.5, 1986: 26.0, 1987: 26.0, 1988: 26.0, 1989: 26.5,
    **{y: 27.5 for y in range(1990, 2011)},
}
# Reference CPI: 2024 annual average, computed from the downloaded series, so
# real-dollar columns are stated in 2024 dollars.
REF_YEAR = 2024


def annual(path, col, how="mean"):
    df = pd.read_csv(path)
    df.columns = ["date", col]
    df["date"] = pd.to_datetime(df["date"])
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df["year"] = df.dt if False else df["date"].dt.year
    g = df.groupby("year")[col]
    out = g.sum(min_count=12) if how == "sum" else g.mean()
    # Partial current year would understate a sum and noise a mean; keep only
    # years with all 12 months for sums, >=6 months for means.
    counts = df.dropna(subset=[col]).groupby("year")[col].count()
    keep = counts[counts >= (12 if how == "sum" else 6)].index
    return out.loc[out.index.isin(keep)]


def main():
    os.makedirs(OUT, exist_ok=True)

    gas = annual(os.path.join(EXT, "fred_gas_price.csv"), "gas_nominal_usd_gal")
    cpi = annual(os.path.join(EXT, "fred_cpi_all.csv"), "cpi_all")
    cpiveh = annual(os.path.join(EXT, "fred_cpi_newveh.csv"), "cpi_new_vehicles")
    vmt = annual(os.path.join(EXT, "fred_vmt.csv"), "vmt_million_miles", how="sum")

    ctx = pd.concat([gas, cpi, cpiveh, vmt], axis=1)
    ctx.index.name = "year"
    ctx = ctx.reset_index()

    ref_cpi = float(ctx.loc[ctx.year == REF_YEAR, "cpi_all"].iloc[0])
    ctx["gas_real_2024_usd_gal"] = ctx.gas_nominal_usd_gal * ref_cpi / ctx.cpi_all
    # New-vehicle prices relative to everything else: the new-vehicle CPI
    # deflated by all-items CPI, indexed to 1975 = 100.
    rel = ctx.cpi_new_vehicles / ctx.cpi_all
    base = float(rel[ctx.year == 1975].iloc[0])
    ctx["new_vehicle_real_price_index_1975"] = 100 * rel / base
    ctx["cafe_car_standard_mpg"] = ctx.year.map(CAFE_CAR_STANDARD)

    ctx = ctx[ctx.year >= 1970].reset_index(drop=True)
    ctx.to_csv(os.path.join(OUT, "context_annual.csv"), index=False, encoding="utf-8")

    with open(os.path.join(REPORTS, "06_external_sources.md"), "w", encoding="utf-8") as f:
        f.write(
            "# External Context Sources\n\n"
            "Generated by 06_external.py. One row per calendar year in "
            "outputs/context_annual.csv.\n\n"
            "| Column | Source | Series | Units | Coverage |\n|---|---|---|---|---|\n"
            "| `gas_nominal_usd_gal` | BLS via FRED | APU000074714 | $/gal, unleaded regular, annual mean of monthly | 1976+ |\n"
            "| `gas_real_2024_usd_gal` | derived | | 2024 dollars via CPI-U | 1976+ |\n"
            "| `cpi_all` | BLS via FRED | CPIAUCSL | index, annual mean | 1947+ |\n"
            "| `cpi_new_vehicles` | BLS via FRED | CUUR0000SETA01 | index, annual mean | 1953+ |\n"
            "| `new_vehicle_real_price_index_1975` | derived | | new-vehicle CPI / all-items CPI, 1975=100 | 1975+ |\n"
            "| `vmt_million_miles` | FHWA via FRED | TRFVOLUSM227NFWA | million vehicle-miles, annual sum (12-month-complete years only) | 1970+ |\n"
            "| `cafe_car_standard_mpg` | NHTSA published standards | 49 USC 32902 era | MPG (2-cycle CAFE basis), passenger cars | 1978-2010; null after: footprint-based, no single value |\n\n"
            "Caveats:\n\n"
            "- Calendar year vs model year: model-year N vehicles sell across "
            "calendar N-1..N. Joining calendar context to model-year fleet "
            "data is an approximation; do not read single-year wiggles as "
            "causal, read multi-year swings.\n"
            "- Gas price series starts 1976 (unleaded); 1975 has no value.\n"
            "- CAFE standard values are the passenger-car national standards; "
            "light trucks had separate, lower standards not included here. "
            "Compare the standard ONLY against `cafe_2cycle_mpg` (same test "
            "basis), never against real-world MPG.\n"
            "- `new_vehicle_real_price_index_1975` uses the BLS new-vehicle "
            "CPI, which is hedonically quality-adjusted: its decline means "
            "price per unit of quality fell, NOT that sticker prices fell. "
            "Do not present it as 'cars got cheaper' without that framing.\n"
        )

    print(f"wrote outputs/context_annual.csv ({len(ctx)} years, "
          f"{ctx.year.min()}-{ctx.year.max()})")
    for y in (1980, 2008, 2022, 2024):
        r = ctx[ctx.year == y].iloc[0]
        print(y, "| gas nominal", round(r.gas_nominal_usd_gal, 2),
              "| real 2024$", round(r.gas_real_2024_usd_gal, 2),
              "| vmt B mi", round(r.vmt_million_miles / 1000, 0),
              "| veh price idx", round(r.new_vehicle_real_price_index_1975, 1))


if __name__ == "__main__":
    main()
