"""22_mympg_analysis.py -- driver-reported real-world MPG vs the window
sticker, vehicle by vehicle.

Joins external/mympg_cache.jsonl (My MPG user-shared summaries) to
vehicles.csv label values (comb08). Writes:

  outputs/mympg_vs_label.csv     one row per vehicle with both numbers
  reports/22_mympg.md            coverage, ratio distributions, era and
                                 powertrain splits, selection caveats
  charts/fig32_drivers_vs_label.png

Selection caveat carried everywhere: My MPG reporters are self-selected
(enthusiasts, hypermilers, people with a grievance), so levels are
indicative; the CROSS-VEHICLE PATTERN (who beats the label, who misses)
is the defensible object.
"""

import io
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "outputs")
REPORTS = os.path.join(HERE, "reports")
CHARTS = os.path.join(HERE, "charts")
CACHE = os.path.join(HERE, "external", "mympg_cache.jsonl")

S1, S2, S3, S5 = "#2a78d6", "#eb6834", "#1baf7a", "#e87ba4"
SURFACE, INK, INK2 = "#fcfcfb", "#0b0b0b", "#52514e"
MUTED, GRID, BASELINE = "#898781", "#e1e0d9", "#c3c2b7"

plt.rcParams.update({
    "font.family": ["Segoe UI", "DejaVu Sans", "sans-serif"],
    "figure.facecolor": SURFACE, "axes.facecolor": SURFACE,
    "savefig.facecolor": SURFACE, "axes.edgecolor": BASELINE,
    "axes.linewidth": 0.8, "axes.grid": True, "grid.color": GRID,
    "grid.linewidth": 0.8, "xtick.color": MUTED, "ytick.color": MUTED,
    "text.color": INK, "axes.labelcolor": INK2, "axes.titlecolor": INK,
    "font.size": 11,
})


def load_cache():
    rows = []
    with open(CACHE, encoding="utf-8") as f:
        for line in f:
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    c = pd.DataFrame(rows)
    n_err = int(c.get("error").notna().sum()) if "error" in c else 0
    c = c[c.get("error").isna()] if "error" in c else c
    for col in ("avgMpg", "recordCount", "maxMpg", "minMpg"):
        if col in c:
            c[col] = pd.to_numeric(c[col], errors="coerce")
    c = c.dropna(subset=["avgMpg"])
    c = c[c.avgMpg > 0]
    return c, n_err


def powertrain(row):
    if row.fuelType1 == "Diesel":
        return "Diesel"
    if isinstance(row.atvType, str) and row.atvType == "Hybrid":
        return "Hybrid"
    return "Gasoline"


def main():
    os.makedirs(CHARTS, exist_ok=True)
    cache, n_err = load_cache()
    veh = pd.read_csv(os.path.join(HERE, "vehicles.csv"), low_memory=False)
    v = veh[["id", "year", "make", "model", "comb08", "fuelType1", "atvType",
             "VClass"]].copy()
    m = cache.merge(v, left_on="vehicleId", right_on="id", how="inner")
    m = m[(m.comb08 > 0) & (m.fuelType1 != "Electricity")]
    m["ratio"] = m.avgMpg / m.comb08
    m["powertrain"] = m.apply(powertrain, axis=1)
    m["era"] = np.where(m.year >= 2008, "2008+ (5-cycle labels)",
                        "pre-2008 (restated labels)")
    m.to_csv(os.path.join(OUT, "mympg_vs_label.csv"), index=False,
             encoding="utf-8")

    solid = m[m.recordCount >= 5]

    b = io.StringIO()
    b.write("# Driver-Reported MPG vs the Window Sticker\n\n"
            "Generated by 22_mympg_analysis.py. Source: fueleconomy.gov "
            "My MPG shared data, /ws/rest/ympg/shared/ympgVehicle/{id}, "
            "fetched by 21_fetch_mympg.py (resumable cache in external/).\n")
    b.write(f"\n## Coverage\n\n- {len(cache):,} vehicles with user data "
            f"fetched ({n_err} fetch errors); {len(m):,} joined to a label "
            f"value (EVs excluded: MPGe).\n"
            f"- Total driver reports underlying the averages: "
            f"{int(m.recordCount.sum()):,}; median reports per vehicle "
            f"{int(m.recordCount.median())}.\n"
            f"- 'Solid' subset (>= 5 reports): {len(solid):,} vehicles.\n")

    b.write("\n## Do drivers beat the sticker?\n\n")
    for label, g in (("All vehicles", m), ("Solid (>=5 reports)", solid)):
        b.write(f"- {label}: median ratio {g.ratio.median():.3f} "
                f"(mean {g.ratio.mean():.3f}); "
                f"{(g.ratio > 1).mean():.0%} of vehicles beat their label.\n")
    b.write("\nBy era (the 2008 label-method change):\n\n")
    b.write(solid.groupby("era").ratio.describe()[["count", "mean", "50%"]]
            .round(3).to_string() + "\n")
    b.write("\nBy powertrain (solid subset):\n\n")
    b.write(solid.groupby("powertrain").ratio.agg(["count", "median"])
            .round(3).to_string() + "\n")

    b.write("\n## Caveats\n\n"
            "- Self-selected reporters: enthusiasts and careful drivers "
            "over-represented; levels are biased, cross-vehicle patterns "
            "are the defensible object.\n"
            "- avgMpg is the site's harmonic mean of user averages; "
            "record counts vary from 1 to hundreds.\n"
            "- Pre-2008 label values in vehicles.csv are retroactive "
            "5-cycle restatements, so the era split reads 'restated vs "
            "native labels'.\n")

    with open(os.path.join(REPORTS, "22_mympg.md"), "w", encoding="utf-8") as f:
        f.write(b.getvalue())

    # Figure: scatter, solid subset, colored by powertrain.
    fig, ax = plt.subplots(figsize=(9.5, 8))
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    ax.tick_params(length=0)
    lim = (8, 62)
    ax.plot(lim, lim, color=INK2, lw=1.2)
    colors = {"Gasoline": S1, "Hybrid": S5, "Diesel": S2}
    for pt, c in colors.items():
        g = solid[solid.powertrain == pt]
        ax.scatter(g.comb08, g.avgMpg, s=14, c=c, alpha=0.4,
                   edgecolors=SURFACE, linewidths=0.4, label=pt)
    ax.set_xlim(lim)
    ax.set_ylim(lim)
    ax.set_xlabel("Window-sticker combined MPG (comb08)")
    ax.set_ylabel("Driver-reported average MPG (My MPG, harmonic mean)")
    med = solid.ratio.median()
    beat = (solid.ratio > 1).mean()
    ax.text(10, 56, f"{len(solid):,} vehicles, >=5 driver reports each\n"
            f"median real/label ratio {med:.2f}\n"
            f"{beat:.0%} of vehicles beat their sticker",
            fontsize=11, color=INK, fontweight="bold")
    ax.text(47, 41, "45°: drivers match\nthe sticker", fontsize=9.5, color=INK2)
    lg = ax.legend(frameon=False, fontsize=10, loc="lower right")
    for t in lg.get_texts():
        t.set_color(INK2)
    ax.set_title("Above the line: drivers report better than the label. "
                 "Below: worse.", loc="left", fontsize=10.5, color=INK2, pad=8)
    fig.suptitle("What drivers actually report vs what the sticker promised",
                 x=0.01, ha="left", fontsize=15, fontweight="bold")
    fig.text(0.01, 0.012, "fueleconomy.gov My MPG shared data (self-selected "
             "reporters; pattern, not levels). EVs excluded (MPGe).",
             fontsize=8.5, color=MUTED)
    fig.tight_layout(rect=(0, 0.03, 1, 0.94))
    fig.savefig(os.path.join(CHARTS, "fig32_drivers_vs_label.png"), dpi=150)

    print(f"joined {len(m):,} vehicles | solid {len(solid):,} | "
          f"median ratio {m.ratio.median():.3f} | solid median "
          f"{solid.ratio.median():.3f} | beat-label {(m.ratio>1).mean():.0%}")
    print(solid.groupby('powertrain').ratio.median().round(3).to_string())


if __name__ == "__main__":
    main()
