"""23_powertrain_compare.py -- BEV vs Hybrid vs Gasoline, year by year.

Per calendar of model years, per powertrain group, from the fueleconomy.gov
catalog joined to historical energy prices:

  - configuration counts
  - median label efficiency (comb08: MPG for gas/hybrid, MPGe for BEV)
  - median energy cost per mile at THAT year's national prices
    (gas $/gal / MPG; electricity $/kWh x kWh/mile)
  - median BEV rated range (gas/hybrid range is not computable: the catalog
    carries no tank size; stated in the report rather than faked)

Groups follow the user's framing: BEV, Hybrid (non-plug-in), Gasoline.
PHEVs and diesels are excluded (PHEV cost needs utility-factor assumptions;
diesel is 38 configs) and counted in the report.

Outputs: outputs/powertrain_trends.csv, reports/23_powertrain.md
"""

import io
import os

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "outputs")
REPORTS = os.path.join(HERE, "reports")


def group(r):
    if r.fuelType1 == "Hydrogen":
        return "FCEV"
    if r.fuelType1 == "Electricity":
        return "BEV"
    if isinstance(r.atvType, str) and r.atvType == "Plug-in Hybrid":
        return "PHEV"
    if isinstance(r.atvType, str) and r.atvType == "Hybrid":
        return "Hybrid"
    if r.fuelType1 == "Diesel":
        return "Diesel"
    if isinstance(r.fuelType1, str) and "Gasoline" in r.fuelType1:
        return "Gasoline"
    return "Other"


def main():
    v = pd.read_csv(os.path.join(OUT, "catalog_fegov.csv"), low_memory=False)
    f = pd.read_csv(os.path.join(OUT, "context_finance.csv"))
    prices = f.set_index("year")[["gas_nominal_usd_gal", "electricity_usd_kwh"]]

    v = v.copy()
    v["grp"] = v.apply(group, axis=1)
    excluded = v.grp.value_counts()
    d = v[v.grp.isin(["BEV", "Hybrid", "Gasoline", "FCEV"])].merge(
        prices, left_on="year", right_index=True, how="left")
    d = d[d.comb08 > 0]
    # FCEV cost per mile is NaN on purpose: no retail hydrogen price series
    # exists in the project's sources (EIA/BLS/FRED publish none; AFDC's
    # quarterly report lacks a fetchable H2 retail series).
    d["cpm"] = np.select(
        [d.grp == "BEV", d.grp == "FCEV"],
        [d.electricity_usd_kwh * d.combE / 100.0, np.nan],
        default=d.gas_nominal_usd_gal / d.comb08)

    rows = []
    for (yr, g), sub in d.groupby(["year", "grp"]):
        ok = sub.dropna(subset=["cpm"])
        rng = sub[(sub.grp.isin(["BEV", "FCEV"])) & (sub["range"] > 0)]["range"]
        rows.append({
            "year": yr, "group": g, "n_configs": len(sub),
            "median_comb08": sub.comb08.median(),
            "median_cost_per_mile": ok.cpm.median() if len(ok) else np.nan,
            "median_range_mi": rng.median() if len(rng) else np.nan,
            "q1_cost_per_mile": ok.cpm.quantile(.25) if len(ok) else np.nan,
            "q3_cost_per_mile": ok.cpm.quantile(.75) if len(ok) else np.nan,
        })
    t = pd.DataFrame(rows).sort_values(["group", "year"]).round(4)
    t.to_csv(os.path.join(OUT, "powertrain_trends.csv"), index=False,
             encoding="utf-8")

    snap = t[(t.year == 2024)].set_index("group")
    b = io.StringIO()
    b.write("# BEV vs Hybrid vs Gasoline\n\nGenerated by "
            "23_powertrain_compare.py. One row per (model year, powertrain "
            "group) in outputs/powertrain_trends.csv.\n")
    b.write("\n## Definitions and exclusions\n\n"
            "- Groups: BEV (fuelType1 = Electricity), FCEV (Hydrogen), "
            "Hybrid (non-plug-in), Gasoline. FCEV efficiency is MPGe and "
            "its cost per mile is left null: no retail hydrogen price "
            "series exists in the project's sources. Excluded: PHEV "
            f"({excluded.get('PHEV', 0):,} configs; per-mile cost needs "
            "utility-factor assumptions), Diesel "
            f"({excluded.get('Diesel', 0):,}), Other "
            f"({excluded.get('Other', 0):,}).\n"
            "- `median_comb08` is the window-sticker combined value: MPG for "
            "gasoline/hybrid, **MPGe for BEV** -- an energy-equivalence "
            "conversion (33.7 kWh/gal), not the same physical quantity. "
            "Charts must carry that label.\n"
            "- Cost per mile uses each model year's national average prices "
            "(BLS via FRED, from outputs/context_finance.csv): energy only, "
            "no purchase price, depreciation, insurance, or DC-fast "
            "premiums.\n"
            "- BEV `median_range_mi` from the catalog's rated range field. "
            "Gasoline/hybrid driving range is NOT computable from this "
            "catalog (no tank-capacity field); the report says so rather "
            "than inventing a figure.\n"
            "- Average vehicle purchase price by group is not available in "
            "any project dataset (fueleconomy.gov has no MSRP; the BLS "
            "new-vehicle CPI is a hedonic index, not a level). Left out "
            "rather than fabricated.\n")
    b.write("\n## 2024 snapshot\n\n"
            "| Group | configs | label comb (MPG / MPGe) | $ per mile | "
            "$ per 15k mi | median BEV range |\n|---|---|---|---|---|---|\n")
    for g in ("BEV", "FCEV", "Hybrid", "Gasoline"):
        if g not in snap.index:
            continue
        r = snap.loc[g]
        rng = f"{r.median_range_mi:.0f} mi" if pd.notna(r.median_range_mi) else ""
        if pd.notna(r.median_cost_per_mile):
            cost = (f"${r.median_cost_per_mile:.3f} | "
                    f"${r.median_cost_per_mile*15000:,.0f}")
        else:
            cost = "n/a (no H2 price series) | n/a"
        b.write(f"| {g} | {int(r.n_configs)} | {r.median_comb08:.0f} | "
                f"{cost} | {rng} |\n")
    # Price-sensitivity block: hold 2024 median efficiency fixed, sweep each
    # energy price across its observed 2011-2026 range. Sensitivity of cost
    # per mile to price is 1/efficiency; volatility exposure differs because
    # gasoline is a global commodity and electricity a regulated utility.
    w = f[(f.year >= 2011) & (f.year <= 2026)].dropna(
        subset=["gas_nominal_usd_gal", "electricity_usd_kwh"])
    gmin, gmax = w.gas_nominal_usd_gal.min(), w.gas_nominal_usd_gal.max()
    emin, emax = w.electricity_usd_kwh.min(), w.electricity_usd_kwh.max()
    cv_g = w.gas_nominal_usd_gal.std() / w.gas_nominal_usd_gal.mean()
    cv_e = w.electricity_usd_kwh.std() / w.electricity_usd_kwh.mean()
    eff = snap.median_comb08
    kwh_per_mi = 33.7 / eff["BEV"]  # MPGe definition: 33.7 kWh per gallon
    sens = {
        "Gasoline": (gmin / eff["Gasoline"], gmax / eff["Gasoline"]),
        "Hybrid": (gmin / eff["Hybrid"], gmax / eff["Hybrid"]),
        "BEV": (emin * kwh_per_mi, emax * kwh_per_mi),
    }
    b.write("\n## Price sensitivity (2024 median vehicle, observed 2011-2026 "
            "prices)\n\n")
    b.write(f"Gas ${gmin:.2f}-${gmax:.2f}/gal (CV {cv_g:.2f}); electricity "
            f"${emin:.3f}-${emax:.3f}/kWh (CV {cv_e:.2f}).\n\n"
            "| Group | annual cost range @15k mi | swing |\n|---|---|---|\n")
    for grp, (lo, hi) in sens.items():
        b.write(f"| {grp} | ${lo*15000:,.0f} - ${hi*15000:,.0f} | "
                f"${(hi-lo)*15000:,.0f} |\n")
    b.write("\nThe BEV's worst observed-price year beats gasoline's best; "
            "its exposure to price swings is about a quarter of the "
            "gasoline vehicle's. Efficiency held at 2024 medians, so this "
            "isolates the price channel only.\n")
    pd.DataFrame([{"group": g_, "annual_low": round(lo * 15000),
                   "annual_high": round(hi * 15000)}
                  for g_, (lo, hi) in sens.items()]).to_csv(
        os.path.join(OUT, "powertrain_sensitivity.csv"), index=False)

    with open(os.path.join(REPORTS, "23_powertrain.md"), "w",
              encoding="utf-8") as fo:
        fo.write(b.getvalue())

    print(t[t.year.isin([2012, 2018, 2024])]
          [["year", "group", "n_configs", "median_comb08",
            "median_cost_per_mile", "median_range_mi"]].to_string(index=False))


if __name__ == "__main__":
    main()
