"""25_atp_data.py -- new-vehicle average transaction prices (ATP), July 2026,
by category and segment, from Kelley Blue Book / Cox Automotive.

Every number below is transcribed from two published Cox Automotive articles
(text snapshots archived in external/):

  [1] "Kelley Blue Book Report: New-Vehicle Prices Trend Higher in July as
      Incentives Decline and Sales Pace Slows", 2026-08-11,
      https://www.coxautoinc.com/insights/july-2026-atp-report/
      (snapshot: external/cox_kbb_atp_july2026.txt)
  [2] "EV Market Monitor - July 2026", 2026-08-17,
      https://www.coxautoinc.com/insights/ev-market-monitor-july-2026/
      (snapshot: external/cox_ev_monitor_july2026.txt)

ATP = average price actually paid (not MSRP). ICE+ is Cox's non-EV bucket
and INCLUDES hybrids; KBB publishes no hybrid-only ATP in these reports,
which is recorded as a limitation rather than estimated.

Outputs: outputs/atp_july2026.csv, reports/25_atp.md
"""

import io
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "outputs")
REPORTS = os.path.join(HERE, "reports")

ROWS = [
    # kind, label, atp_usd, note, source
    ("category", "Industry (all new vehicles)", 49855,
     "July 2026; MSRP average $51,621; incentives 6.4% of ATP", "[1]"),
    ("category", "EV (battery electric)", 56126,
     "incentives $6,626 = 11.8% of ATP; premium over ICE+ $6,477", "[1][2]"),
    ("category", "ICE+ (non-EV, incl. hybrids)", 49649,
     "derived: EV ATP minus the published $6,477 EV-over-ICE+ premium", "[2]"),
    ("brand", "Tesla", 53891,
     "incentives $5,599 = 10.4% of ATP", "[1]"),
    ("model", "Tesla Model Y", 52500, "approximate, as published", "[2]"),
    ("model", "Tesla Model 3", 50500, "approximate, as published", "[2]"),
    ("segment", "Full-size pickup truck", 66980, "+2.8% YoY", "[1]"),
    ("segment", "Midsize SUV", 50144, "+2.4% YoY", "[1]"),
    ("segment", "Compact SUV", 37745, "+2.7% YoY", "[1]"),
    ("segment", "Subcompact SUV", 31052, "+1.1% YoY", "[1]"),
    ("segment", "Compact car", 27904, "+2.6% YoY", "[1]"),
    ("used", "Used EV (listing price)", 37832,
     "premium over used ICE+ $2,967", "[2]"),
]


def main():
    df = pd.DataFrame(ROWS, columns=["kind", "label", "atp_usd", "note",
                                     "source"])
    df.to_csv(os.path.join(OUT, "atp_july2026.csv"), index=False,
              encoding="utf-8")

    b = io.StringIO()
    b.write("# Average Transaction Prices, July 2026 (KBB / Cox Automotive)\n"
            "\nGenerated by 25_atp_data.py. Values transcribed from the two "
            "cited articles; text snapshots archived in external/ so the "
            "transcription is checkable.\n\n")
    b.write("| Kind | Label | ATP | Note |\n|---|---|---|---|\n")
    for _, r in df.iterrows():
        b.write(f"| {r.kind} | {r.label} | ${r.atp_usd:,} | {r.note} "
                f"{r.source} |\n")
    b.write(
        "\n## Sources\n\n"
        "1. Kelley Blue Book Report, July 2026 ATPs, Cox Automotive, "
        "2026-08-11: https://www.coxautoinc.com/insights/july-2026-atp-report/\n"
        "2. EV Market Monitor, July 2026, Cox Automotive, 2026-08-17: "
        "https://www.coxautoinc.com/insights/ev-market-monitor-july-2026/\n"
        "\n## Limitations\n\n"
        "- ATP is the average price paid for vehicles actually sold: it "
        "mixes list price with sales mix and incentives, and is not an MSRP "
        "average across the catalog.\n"
        "- **No hybrid-only ATP exists in these reports**: Cox's ICE+ bucket "
        "folds hybrids in with gasoline. The three-way BEV/Hybrid/Gasoline "
        "price split the energy-cost analysis uses cannot be completed from "
        "public KBB data; stated rather than estimated.\n"
        "- Single month (July 2026). Cox publishes monthly; a time series "
        "would need the article archive walked backward.\n"
        "- Tesla model figures are published approximations.\n"
        "\n## The one-line takeaway for the deck\n\n"
        "The median new EV costs ~$6,500 more to buy [2] and ~$1,456 less "
        "per year to fuel (fig33/fig36): at that rate the energy savings "
        "alone repay the purchase premium in roughly 4.5 years, before any "
        "maintenance or incentive effects.\n")
    with open(os.path.join(REPORTS, "25_atp.md"), "w", encoding="utf-8") as f:
        f.write(b.getvalue())
    print(df.to_string(index=False))


if __name__ == "__main__":
    main()
