"""29_productivity.py -- design-normalized fuel-economy productivity and a
15-20 year projection.

Idea: raw fleet MPG confounds technology with design drift (weight, power).
Using the final pooled-model elasticities (stage 33, spec F; read from
outputs/pooled_model.json so the pipeline has one source of truth),
re-express every year's fleet MPG as what it would have been AT 2024's fleet
weight and horsepower:

    MPG_norm(t) = MPG(t) * (wt_t / wt_2024)^e_w * (hp_t / hp_2024)^e_h

The fleet series folds BEV MPGe in, which is why the pooled (all-powertrain)
elasticities are the consistent choice here; stage 31's combustion-only
series uses the combustion-only elasticities.

The result is a technology-productivity series: efficiency progress with
the horsepower wars and weight gain removed. Fit exponential growth, then
project 2025-2045 under two documented scenarios (full-history rate and
2005+ rate) with a slope-CI band.

Outputs: outputs/productivity.csv, reports/29_productivity.md,
charts/fig42_productivity_projection.png
"""

import io
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "outputs")
REPORTS = os.path.join(HERE, "reports")
CHARTS = os.path.join(HERE, "charts")

with open(os.path.join(OUT, "pooled_model.json"), encoding="utf-8") as _f:
    _EL = json.load(_f)["final_elasticities"]
EL_W, EL_H = _EL["weight"], _EL["hp"]  # stage-33 final-equation elasticities

S1, S2, S3 = "#2a78d6", "#eb6834", "#1baf7a"
SURFACE, INK, INK2 = "#fcfcfb", "#0b0b0b", "#52514e"
MUT, GRID, BASELINE, WASH = "#898781", "#e1e0d9", "#c3c2b7", "#f0efec"

plt.rcParams.update({
    "font.family": ["Segoe UI", "DejaVu Sans", "sans-serif"],
    "figure.facecolor": SURFACE, "axes.facecolor": SURFACE,
    "savefig.facecolor": SURFACE, "axes.edgecolor": BASELINE,
    "axes.linewidth": 0.8, "axes.grid": True, "grid.color": GRID,
    "grid.linewidth": 0.8, "xtick.color": MUT, "ytick.color": MUT,
    "text.color": INK, "axes.labelcolor": INK2, "axes.titlecolor": INK,
    "font.size": 11,
})


def main():
    os.makedirs(CHARTS, exist_ok=True)
    ac = pd.read_csv(os.path.join(OUT, "analysis_clean.csv"))
    aa = (ac[(ac.manufacturer == "All") & (ac.regulatory_class == "All")
             & (ac.vehicle_type == "All") & (~ac.is_preliminary)]
          .sort_values("model_year")
          .dropna(subset=["real_world_mpg", "weight_lbs", "horsepower_hp"]))
    ref = aa[aa.model_year == 2024].iloc[0]
    aa = aa.assign(mpg_norm=aa.real_world_mpg
                   * (aa.weight_lbs / ref.weight_lbs) ** EL_W
                   * (aa.horsepower_hp / ref.horsepower_hp) ** EL_H)
    t = aa.model_year.values.astype(float)
    ln = np.log(aa.mpg_norm.values)

    r_all = stats.linregress(t, ln)
    m = t >= 2005
    r_rec = stats.linregress(t[m], ln[m])

    proj_years = np.arange(2025, 2046)
    def project(r):
        return np.exp(r.intercept + r.slope * proj_years)
    p_all, p_rec = project(r_all), project(r_rec)
    # Slope-CI band in centered form (years measured from the fit window's
    # mean), so the slope uncertainty is not spuriously applied at year 0.
    t_bar, ln_bar = t[m].mean(), ln[m].mean()
    dz = proj_years - t_bar
    lo = np.exp(ln_bar + (r_rec.slope - 1.96 * r_rec.stderr) * dz)
    hi = np.exp(ln_bar + (r_rec.slope + 1.96 * r_rec.stderr) * dz)

    out = pd.DataFrame({"year": np.concatenate([t, proj_years]),
                        "mpg_norm": np.concatenate([aa.mpg_norm.values,
                                                    np.full(len(proj_years), np.nan)]),
                        "proj_recent": np.concatenate([np.full(len(t), np.nan), p_rec]),
                        "proj_full": np.concatenate([np.full(len(t), np.nan), p_all])})
    out.round(3).to_csv(os.path.join(OUT, "productivity.csv"), index=False)

    g_all = 100 * (np.exp(r_all.slope) - 1)
    g_rec = 100 * (np.exp(r_rec.slope) - 1)
    pts = {int(y): v for y, v in zip(aa.model_year, aa.mpg_norm)}
    path = " -> ".join(f"{pts[y]:.1f}" for y in (1975, 1987, 2004, 2024))
    y87 = aa[aa.model_year == 1987].iloc[0]
    b = io.StringIO()
    b.write("# Design-Normalized Fuel-Economy Productivity\n\n"
            "Generated by 29_productivity.py.\n\n"
            "## Construction\n\n"
            f"MPG_norm(t) = fleet real-world MPG x (weight_t/weight_2024)^{EL_W} "
            f"x (HP_t/HP_2024)^{EL_H}, elasticities from the stage-33 final "
            "equation (pooled, all powertrains). Interpretation: what each "
            "year's technology would have delivered at 2024's fleet weight "
            "and power.\n\n"
            f"Worked example, 1987: raw {y87.real_world_mpg:.1f} MPG at "
            f"{y87.weight_lbs:.0f} lbs / {y87.horsepower_hp:.0f} HP vs 2024's "
            f"{ref.weight_lbs:.0f} lbs / {ref.horsepower_hp:.0f} HP -> "
            f"{y87.real_world_mpg:.1f} x ({y87.weight_lbs:.0f}/{ref.weight_lbs:.0f})^{EL_W} "
            f"x ({y87.horsepower_hp:.0f}/{ref.horsepower_hp:.0f})^{EL_H} = "
            f"{y87.real_world_mpg:.1f} x {(y87.weight_lbs/ref.weight_lbs)**EL_W:.3f} "
            f"x {(y87.horsepower_hp/ref.horsepower_hp)**EL_H:.3f} = "
            f"{y87.mpg_norm:.1f}.\n\n"
            "## Findings\n\n"
            f"- The 1987-2004 MPG trough disappears: normalized productivity "
            f"is monotone ({path} for 1975/1987/2004/2024). Raw MPG fell in "
            "the middle years only because the gains were spent on weight "
            "and power.\n"
            f"- Growth is close to exponential and startlingly steady: "
            f"**{g_all:.2f}%/yr over 1975-2024 (R2 = {r_all.rvalue**2:.3f})**; "
            f"{g_rec:.2f}%/yr over 2005-2024 (R2 = {r_rec.rvalue**2:.3f}).\n\n"
            "## Projection, holding design constant at 2024\n\n"
            "| Year | at 2005-2024 rate | at 1975-2024 rate |\n|---|---|---|\n")
    for yr in (2030, 2035, 2040, 2045):
        i = list(proj_years).index(yr)
        b.write(f"| {yr} | {p_rec[i]:.1f} | {p_all[i]:.1f} |\n")
    b.write(
        "\n## Caveats (present with the chart)\n\n"
        "- Elasticities are estimated on the 2024 cross-section and applied "
        "to five decades: a stability assumption, partially supported by the "
        "era refits (R2 0.71-0.78 across 2000+/2020+ windows).\n"
        "- Fleet real-world MPG folds EV energy-equivalents in, so part of "
        "post-2011 'productivity' is electrification mix, not combustion "
        "technology; the projection inherits that blend and effectively "
        "assumes the electrification pace continues.\n"
        "- Straight-line extrapolation in log space: no physics ceiling, no "
        "policy scenario. The two rates bracket, not bound, the future.\n"
        "- Slope-CI band on the chart reflects fit uncertainty only, not "
        "scenario uncertainty, which dominates.\n")
    with open(os.path.join(REPORTS, "29_productivity.md"), "w",
              encoding="utf-8") as f:
        f.write(b.getvalue())

    fig, ax = plt.subplots(figsize=(11, 6.4))
    for side in ("top", "right", "left"):
        ax.spines[side].set_visible(False)
    ax.tick_params(length=0)
    ax.grid(axis="x", visible=False)
    ax.axvspan(1987, 2004, color=WASH, zorder=0)
    ax.plot(t, aa.real_world_mpg.values, color=BASELINE, lw=1.6)
    ax.plot(t, aa.mpg_norm.values, color=S1, lw=2.2)
    ax.fill_between(proj_years, lo, hi, color="#cde2fb", alpha=0.7)
    ax.plot(proj_years, p_rec, color=S1, lw=2.2, ls=(0, (4, 2)))
    ax.plot(proj_years, p_all, color=S3, lw=1.8, ls=(0, (2, 2)))
    ax.text(1975.5, 24.3, "raw fleet MPG\n(the visible trough)", color=MUT,
            fontsize=10)
    ax.text(1994, 11.6, "normalized to 2024 design:\nno trough, "
            f"+{g_all:.1f}%/yr for 50 years", color=S1, fontweight="bold",
            fontsize=10.5)
    ax.annotate(f"2045 at 2005-2024 rate: {p_rec[-1]:.0f}",
                xy=(2045, p_rec[-1]), xytext=(2028, 47), fontsize=10,
                color=S1, fontweight="bold",
                arrowprops=dict(arrowstyle="-", color=MUT, lw=0.8))
    ax.annotate(f"at 50-year rate: {p_all[-1]:.0f}",
                xy=(2045, p_all[-1]), xytext=(2035.5, 30), fontsize=10,
                color=S3,
                arrowprops=dict(arrowstyle="-", color=MUT, lw=0.8))
    ax.set_ylim(5, 55)
    ax.set_title("Fleet MPG re-expressed at constant 2024 weight and "
                 f"horsepower (elasticities {EL_W:.3f} / {EL_H:.3f}, pooled "
                 "equation); dashed = projection, band = slope 95% CI",
                 loc="left", fontsize=10.5, color=INK2, pad=8)
    fig.suptitle("Hold the design constant and efficiency never stalled: "
                 f"+{g_all:.1f}%/yr for 50 years, ~{p_rec[-1]:.0f} MPG by 2045",
                 x=0.01, ha="left", fontsize=15, fontweight="bold")
    fig.text(0.01, 0.012, "EPA Trends fleet data + stage-33 elasticities. "
             "Projection assumes trend continuation; EV mix folded in; see "
             "reports/29_productivity.md caveats.", fontsize=8.5, color=MUT)
    fig.tight_layout(rect=(0, 0.04, 1, 0.92))
    fig.savefig(os.path.join(CHARTS, "fig42_productivity_projection.png"),
                dpi=150)
    print(f"full-rate {g_all:.2f}%/yr R2 {r_all.rvalue**2:.3f} | "
          f"recent {g_rec:.2f}%/yr | 2035 {p_rec[list(proj_years).index(2035)]:.1f} "
          f"| 2045 {p_rec[-1]:.1f} (recent) / {p_all[-1]:.1f} (full)")


if __name__ == "__main__":
    main()
